import fs from 'node:fs'
import process from 'node:process'
import { Profile } from '@garmin/fitsdk'
import { ESLint } from 'eslint'

interface GarminField {
  num: number
  name: string
  type: string
  baseType: string
  array: boolean
  scale: number | number[]
  offset: number | number[]
  units: string | string[]
}

interface GarminMessage {
  num: number
  name: string
  fields: Record<string, GarminField>
}

interface GeneratedField {
  field: string
  type: string
  baseType: string
  array: boolean
  scale: number
  offset: number
  units: string
}

interface GeneratedMessage {
  name: string
  [fieldId: number]: GeneratedField
}

const fieldNameCorrections: Record<string, string> = {
  cadenceZoneHighBondary: 'cadence_zone_high_boundary',
}

function snakeCase(value: string): string {
  if (/^(?:uint|sint|float)\d+z?$/i.test(value)) {
    return value.toLowerCase()
  }

  return value
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([a-z])(\d)/gi, '$1_$2')
    .toLowerCase()
}

function scalar<T>(value: T | T[], fallback: T): T {
  return Array.isArray(value) ? (value[0] ?? fallback) : value
}

function generateMessages(): Record<number, GeneratedMessage> {
  const messages = Profile.messages as unknown as Record<string, GarminMessage>

  return Object.fromEntries(
    Object.values(messages)
      .sort((left, right) => left.num - right.num)
      .map((message) => {
        const fields = Object.values(message.fields)
          .sort((left, right) => left.num - right.num)
          .map((field) => {
            const fieldName
              = fieldNameCorrections[field.name] ?? snakeCase(field.name)
            return [field.num, {
              field: fieldName,
              type: snakeCase(field.type),
              baseType: snakeCase(field.baseType),
              array: field.array && field.baseType !== 'string',
              scale: scalar(field.scale, 1),
              // The SDK stores the FIT profile offset. This parser's legacy
              // formatter adds offsets, so retain its equivalent signed form.
              offset: -scalar(field.offset, 0),
              units: scalar(field.units, ''),
            }]
          })

        return [message.num, {
          name: snakeCase(message.name),
          ...Object.fromEntries(fields),
        }]
      }),
  )
}

function generateTypes(): Record<string, Record<number, string>> {
  const types = Profile.types as unknown as Record<string, Record<number, string>>

  return Object.fromEntries(
    Object.entries(types)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([typeName, values]) => [
        snakeCase(typeName),
        Object.fromEntries(
          Object.entries(values)
            .sort(([left], [right]) => Number(left) - Number(right))
            .map(([value, name]) => [value, snakeCase(name)]),
        ),
      ]),
  )
}

async function main(): Promise<void> {
  const outputPath = `${import.meta.dirname}/../src/garmin_profile.generated.ts`
  const generated = `/*
 * Generated from @garmin/fitsdk ${Profile.version.major}.${Profile.version.minor}.${Profile.version.patch}.
 * Do not edit this file directly; run "npm run codegen:profile".
 */
import type { Message } from './fit.js'

export const GARMIN_PROFILE_VERSION = ${JSON.stringify(Profile.version, null, 2)} as const

export const GARMIN_MESSAGES: Record<number, Message> = ${JSON.stringify(generateMessages(), null, 2)}

export const GARMIN_TYPES: Record<string, Record<number, string | number>> = ${JSON.stringify(generateTypes(), null, 2)}
`
  const eslint = new ESLint({ fix: true })
  const [result] = await eslint.lintText(generated, { filePath: outputPath })
  const output = result.output ?? generated

  if (process.argv.includes('--check')) {
    if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, 'utf8') !== output) {
      console.error(
        'src/garmin_profile.generated.ts is out of date; run npm run codegen and commit the result.',
      )
      process.exitCode = 1
    }
  }
  else {
    fs.writeFileSync(outputPath, output)
  }
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
